services:
  triton:
    image: "nvcr.io/nvidia/tritonserver:24.06-py3"
    command: ["tritonserver", "--model-repository=/models"]
    volumes:
      - "./onnx-mobilenetv2/models:/models:Z"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
